# Generated by Django 4.2.1 on 2023-06-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hija',
            fields=[
                ('abuela_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testmeta.abuela')),
            ],
            options={
                'abstract': False,
            },
            bases=('testmeta.abuela',),
        ),
        migrations.CreateModel(
            name='Nieta',
            fields=[
                ('hija_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testmeta.hija')),
            ],
            options={
                'abstract': False,
            },
            bases=('testmeta.hija',),
        ),
    ]
