# Generated by Django 4.2.1 on 2023-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nieta',
            name='apodito',
            field=models.CharField(default='ChibiTemp', max_length=10),
            preserve_default=False,
        ),
    ]
