# Generated by Django 4.2.1 on 2023-06-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmeta', '0002_nieta_apodito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nieto',
            fields=[
                ('hija_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testmeta.hija')),
                ('renombrado', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('testmeta.hija',),
        ),
    ]
